CREATE DATABASE IF NOT EXISTS to_do_list;
DROP TABLE IF EXISTS task;
CREATE TABLE IF NOT EXISTS task(

    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    dsc VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()

);

SELECT * FROM task;
